# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'products.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_products(object):
    def setupUi(self, products):
        products.setObjectName("products")
        products.resize(693, 406)
        products.setStyleSheet("QWidget#products{\n"
"    background-color:rgb(0, 124, 124);\n"
"}\n"
"QLabel{\n"
"    font: 15px  \"Centular\";\n"
"}\n"
"QPushButton{\n"
"    font: 15px  \"Centular\";\n"
"    background-color:rgb(0, 124, 124);\n"
"}\n"
"\n"
"QLabel#h_1 ,QLabel#h_2, QLabel#h_3{\n"
"    font: bold 16px  \"Centular\";\n"
"}\n"
"\n"
"QFrame#mainframe_1, QFrame#mainframe_2,  QFrame#mainframe_3{\n"
"    background-color:rgb(51, 152, 152);\n"
"    border-radius:6px;\n"
"}\n"
"\n"
"QComboBox,QSpinBox,QLineEdit{\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:#000;\n"
"    border-radius:3px;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(products)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.mainframe_1 = QtWidgets.QFrame(products)
        self.mainframe_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe_1.setObjectName("mainframe_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainframe_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.mainframe_1)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.h_1 = QtWidgets.QLabel(self.frame_4)
        self.h_1.setObjectName("h_1")
        self.gridLayout_3.addWidget(self.h_1, 0, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ButtonAddProduct = QtWidgets.QPushButton(self.frame_7)
        self.ButtonAddProduct.setMinimumSize(QtCore.QSize(125, 0))
        self.ButtonAddProduct.setMaximumSize(QtCore.QSize(125, 16777215))
        self.ButtonAddProduct.setObjectName("ButtonAddProduct")
        self.gridLayout_4.addWidget(self.ButtonAddProduct, 0, 0, 1, 1)
        self.buttonClear = QtWidgets.QPushButton(self.frame_7)
        self.buttonClear.setMinimumSize(QtCore.QSize(125, 0))
        self.buttonClear.setMaximumSize(QtCore.QSize(125, 16777215))
        self.buttonClear.setObjectName("buttonClear")
        self.gridLayout_4.addWidget(self.buttonClear, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_7, 1, 2, 6, 1, QtCore.Qt.AlignLeft)
        self.fieldName = QtWidgets.QLineEdit(self.frame_4)
        self.fieldName.setMinimumSize(QtCore.QSize(125, 25))
        self.fieldName.setMaximumSize(QtCore.QSize(300, 25))
        self.fieldName.setObjectName("fieldName")
        self.gridLayout_3.addWidget(self.fieldName, 2, 0, 1, 1)
        self.fieldStock = QtWidgets.QSpinBox(self.frame_4)
        self.fieldStock.setMinimumSize(QtCore.QSize(125, 25))
        self.fieldStock.setMaximumSize(QtCore.QSize(300, 25))
        self.fieldStock.setObjectName("fieldStock")
        self.gridLayout_3.addWidget(self.fieldStock, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 1, 1, 1)
        self.fieldBrand = QtWidgets.QComboBox(self.frame_4)
        self.fieldBrand.setMinimumSize(QtCore.QSize(125, 25))
        self.fieldBrand.setMaximumSize(QtCore.QSize(300, 25))
        self.fieldBrand.setObjectName("fieldBrand")
        self.gridLayout_3.addWidget(self.fieldBrand, 4, 0, 1, 1)
        self.fieldPrize = QtWidgets.QLineEdit(self.frame_4)
        self.fieldPrize.setMinimumSize(QtCore.QSize(125, 25))
        self.fieldPrize.setMaximumSize(QtCore.QSize(300, 25))
        self.fieldPrize.setObjectName("fieldPrize")
        self.gridLayout_3.addWidget(self.fieldPrize, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 5, 0, 1, 1)
        self.fieldCategory = QtWidgets.QComboBox(self.frame_4)
        self.fieldCategory.setMinimumSize(QtCore.QSize(125, 25))
        self.fieldCategory.setMaximumSize(QtCore.QSize(300, 25))
        self.fieldCategory.setObjectName("fieldCategory")
        self.gridLayout_3.addWidget(self.fieldCategory, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 0, 1, 1, 1)
        self.tableProducts = QtWidgets.QTableWidget(self.mainframe_1)
        self.tableProducts.setObjectName("tableProducts")
        self.tableProducts.setColumnCount(0)
        self.tableProducts.setRowCount(0)
        self.tableProducts.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tableProducts, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout.addWidget(self.mainframe_1, 0, 0, 1, 2)
        self.mainframe_2 = QtWidgets.QFrame(products)
        self.mainframe_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe_2.setObjectName("mainframe_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.mainframe_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableBrands = QtWidgets.QTableWidget(self.mainframe_2)
        self.tableBrands.setObjectName("tableBrands")
        self.tableBrands.setColumnCount(0)
        self.tableBrands.setRowCount(0)
        self.tableBrands.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tableBrands, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.frame_5 = QtWidgets.QFrame(self.mainframe_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.h_2 = QtWidgets.QLabel(self.frame_5)
        self.h_2.setObjectName("h_2")
        self.gridLayout_6.addWidget(self.h_2, 0, 0, 1, 1)
        self.fieldNewBrand = QtWidgets.QLineEdit(self.frame_5)
        self.fieldNewBrand.setMinimumSize(QtCore.QSize(125, 25))
        self.fieldNewBrand.setMaximumSize(QtCore.QSize(300, 25))
        self.fieldNewBrand.setObjectName("fieldNewBrand")
        self.gridLayout_6.addWidget(self.fieldNewBrand, 1, 0, 1, 1)
        self.buttonAddBrand = QtWidgets.QPushButton(self.frame_5)
        self.buttonAddBrand.setMinimumSize(QtCore.QSize(125, 0))
        self.buttonAddBrand.setMaximumSize(QtCore.QSize(125, 16777215))
        self.buttonAddBrand.setObjectName("buttonAddBrand")
        self.gridLayout_6.addWidget(self.buttonAddBrand, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_5.addWidget(self.frame_5, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout.addWidget(self.mainframe_2, 1, 0, 1, 1)
        self.mainframe_3 = QtWidgets.QFrame(products)
        self.mainframe_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe_3.setObjectName("mainframe_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.mainframe_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableCategories = QtWidgets.QTableWidget(self.mainframe_3)
        self.tableCategories.setObjectName("tableCategories")
        self.tableCategories.setColumnCount(0)
        self.tableCategories.setRowCount(0)
        self.tableCategories.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.tableCategories, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.frame_6 = QtWidgets.QFrame(self.mainframe_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.h_3 = QtWidgets.QLabel(self.frame_6)
        self.h_3.setObjectName("h_3")
        self.gridLayout_8.addWidget(self.h_3, 0, 0, 1, 1)
        self.fieldNewCategory = QtWidgets.QLineEdit(self.frame_6)
        self.fieldNewCategory.setMinimumSize(QtCore.QSize(125, 25))
        self.fieldNewCategory.setMaximumSize(QtCore.QSize(300, 25))
        self.fieldNewCategory.setObjectName("fieldNewCategory")
        self.gridLayout_8.addWidget(self.fieldNewCategory, 1, 0, 1, 1)
        self.buttonAddCategory = QtWidgets.QPushButton(self.frame_6)
        self.buttonAddCategory.setMinimumSize(QtCore.QSize(125, 0))
        self.buttonAddCategory.setMaximumSize(QtCore.QSize(125, 16777215))
        self.buttonAddCategory.setObjectName("buttonAddCategory")
        self.gridLayout_8.addWidget(self.buttonAddCategory, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_7.addWidget(self.frame_6, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout.addWidget(self.mainframe_3, 1, 1, 1, 1)

        self.retranslateUi(products)
        QtCore.QMetaObject.connectSlotsByName(products)

    def retranslateUi(self, products):
        _translate = QtCore.QCoreApplication.translate
        products.setWindowTitle(_translate("products", "Form"))
        self.h_1.setText(_translate("products", "New Product"))
        self.label_2.setText(_translate("products", "Product Name"))
        self.label_5.setText(_translate("products", "Current Stock"))
        self.ButtonAddProduct.setText(_translate("products", "Add"))
        self.buttonClear.setText(_translate("products", "Clear"))
        self.label_3.setText(_translate("products", "Brand"))
        self.label_6.setText(_translate("products", "Prize/Unit"))
        self.label_4.setText(_translate("products", "Category"))
        self.h_2.setText(_translate("products", "NewBrand"))
        self.buttonAddBrand.setText(_translate("products", "Add"))
        self.h_3.setText(_translate("products", "New Category"))
        self.buttonAddCategory.setText(_translate("products", "Add"))
