# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sales.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sales(object):
    def setupUi(self, sales):
        sales.setObjectName("sales")
        sales.resize(400, 300)

        self.retranslateUi(sales)
        QtCore.QMetaObject.connectSlotsByName(sales)

    def retranslateUi(self, sales):
        _translate = QtCore.QCoreApplication.translate
        sales.setWindowTitle(_translate("sales", "Form"))
